---
- name: "Ensure Claude Code User directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.claude"
    state: directory
    mode: '0755'

- name: "Find Claude config files (flat)"
  ansible.builtin.find:
    paths: "{{ config_dir_abs_path }}/claude"
    patterns:
      - "*.json"
      - "*.md"
    file_type: file
    recurse: no
  register: claude_files_flat

- name: "Symlink Claude config files (flat)"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.claude/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ claude_files_flat.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: "Find Claude config directories (recursive)"
  ansible.builtin.find:
    paths: "{{ config_dir_abs_path }}/claude"
    file_type: directory
    recurse: no
    patterns:
      - "commands"
      - "templates"
  register: claude_dirs

- name: "Symlink Claude config directories (recursive)"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.claude/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ claude_dirs.files }}"
  loop_control:
    label: "{{ item.path | basename }}"