---
- name: "Ensure Claude configuration directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.claude"
    state: directory
    mode: '0755'
  tags:
    - claude

- name: "Find Claude config files (flat)"
  ansible.builtin.find:
    paths: "{{ config_dir_abs_path }}/aiding/claude"
    patterns:
      - "*.json"
      - "*.md"
    file_type: file
    recurse: no
  register: claude_files_flat
  tags:
    - claude

- name: "Symlink Claude config files (flat)"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.claude/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ claude_files_flat.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags:
    - claude

- name: "Find Claude config directories (recursive)"
  ansible.builtin.find:
    paths: "{{ config_dir_abs_path }}/aiding/claude"
    file_type: directory
    recurse: no
    patterns:
      - "templates"
  register: claude_dirs
  tags:
    - claude

- name: "Symlink Claude config directories (recursive)"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.claude/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ claude_dirs.files | default([]) }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags:
    - claude

- name: "Create Claude commands directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.claude/commands"
    state: directory
    mode: '0755'
  tags:
    - claude

- name: "Symlink Claude AGENTS file"
  ansible.builtin.file:
    src: "{{ config_dir_abs_path }}/aiding/claude/CLAUDE.md"
    dest: "{{ ansible_env.HOME }}/.claude/CLAUDE.md"
    state: link
    force: true
  tags:
    - claude
