description = "Activate voice completion notification using Voicevox MCP."

prompt = """
Activate the feature to notify task completion with voice using Voicevox MCP. Set speaker to 2 and use speedScale=1.3. Respond only with "Voice completion notification activated." if successful.
"""