description = "Deactivate voice completion notification."

prompt = """
Deactivate the feature to notify task completion with voice. Respond only with "Voice completion notification deactivated." if successful.
"""