description = "Create or update documentation in Serena's memory system"

prompt = """
# /docs-srn - Document in Serena Memory

Create or update documentation in Serena's memory system using the provided arguments.

Arguments provided: {{args}}

Use the write_memory tool to store the content under the specified memory name. 
All memory content must be written in English only, regardless of user's language preference.
"""