---
- name: "Install formulae packages from Brewfile (profile-specific or common fallback)"
  ansible.builtin.command:
    cmd: "brew bundle --file={{ brewfile_path }}"
  register: brew_bundle_result
  changed_when: "'Installing' in brew_bundle_result.stdout"
  vars:
    brewfile_path: "{{ lookup('first_found', brewfile_candidates) }}"
    brewfile_candidates:
      - "{{ repo_root_path }}/config/profiles/{{ profile }}/brew/formulae/Brewfile"
      - "{{ config_dir_abs_path }}/brew/formulae/Brewfile"
