---
- name: "Install formulae packages from Brewfile (profile-specific or common fallback)"
  ansible.builtin.shell: |
    if [ -f "{{ repo_root_path }}/config/profiles/{{ profile }}/brew/formulae/Brewfile" ]; then
      brew bundle --file="{{ repo_root_path }}/config/profiles/{{ profile }}/brew/formulae/Brewfile"
    else
      brew bundle --file="{{ config_dir_abs_path }}/brew/formulae/Brewfile"
    fi
  register: brew_bundle_result
  changed_when: "'Installing' in brew_bundle_result.stdout"