---
- name: "Install Homebrew formulae (CLI tools)"
  include_tasks: formulae.yml
  when: brew_install_formulae | default(true)
  tags: [brew, brew-formulae]

- name: "Install Homebrew casks (GUI apps)"
  include_tasks: cask.yml
  when: brew_install_cask | default(true)
  tags: [brew, brew-cask]