---
- name: "Install git"
  community.general.homebrew:
    name: git
    state: present

- name: "Ensure .config/git directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/git"
    state: directory
    mode: "0755"

- name: "Copy .gitconfig"
  ansible.builtin.copy:
    src: "{{ role_path }}/config/common/git/.gitconfig"
    dest: "{{ ansible_env.HOME }}/.config/git/config"
    force: true
    mode: "0644"

- name: "Symlink .gitignore_global"
  ansible.builtin.file:
    src: "{{ role_path }}/config/common/git/.gitignore_global"
    dest: "{{ ansible_env.HOME }}/.gitignore_global"
    state: link
    force: true

- name: "Set global git config for excludesfile"
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_env.HOME }}/.gitignore_global"

- name: "Ensure ~/.scripts/python directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.scripts/python"
    state: directory
    mode: "0755"

- name: "Find git helper scripts"
  ansible.builtin.find:
    paths: "{{ repo_root_path }}/ansible/scripts/vcs"
    patterns: "*.py"
    file_type: file
  register: vcs_git_helper_scripts

- name: "Symlink git helper scripts to ~/.scripts/python"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.scripts/python/{{ item.path | basename }}"
    state: link
    force: true
    mode: "0755"
  loop: "{{ vcs_git_helper_scripts.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
