[project]
name = "menv"
version = "0.1.0"
description = "My Entire macOS Environment"
authors = [{ name = "akitorahayashi" }]
requires-python = ">=3.12,<3.13"
dependencies = [
    "ansible>=10.0.0,<11.0.0",
    "httpx>=0.27.0,<1.0.0",
    "pyyaml>=6.0,<7.0",
    "rich>=13.9.0,<14.0.0",
    "typer>=0.12.3,<0.13.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1,<9.0.0",
    "pytest-xdist>=3.8.0,<4.0.0",
    "black>=25.1.0,<26.0.0",
    "ruff>=0.12.10,<1.0.0",
    "ansible-lint>=25.0.0",
]
mlx = [
    "mlx-lm>=0.28.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "-v -s --tb=short"

[tool.black]
target-version = ['py312']
exclude = '''
/(
    \.git
    | \.mypy_cache
    | \.uv-cache
    | \.venv
    | venv
    | env
    | build
    | dist
    | .*/(bin|lib|share|etc)
    | .*/pyvenv\.cfg
)/
'''

[tool.ruff]
target-version = "py312"
exclude = [
    "__pycache__",
    "*.pyc",
    ".uv-cache",
    ".venv",
    "venv",
    "env",
    "*/bin/**",
    "*/lib/**",
    "*/share/**",
    "*/etc/**",
    "*/pyvenv.cfg"
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

