[project]
name = "environment"
version = "0.1.0"
description = "Ansible playbook for my entire MacOS environment."
authors = [{ name = "akitorahayashi", email = "atora.has75@gmail.com" }]
requires-python = ">=3.12,<4.0"

[dependency-groups]
dev = [
    "pytest>=8.4.1,<9.0.0",
    "pytest-xdist>=3.8.0,<4.0.0",
    "pyyaml>=6.0,<7.0",
    "black>=25.1.0,<26.0.0",
    "ruff>=0.12.10,<1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v -s --tb=short"

[tool.black]
target-version = ['py312']
exclude = '''
/(
    \.git
    | \.mypy_cache
    | \.uv-cache
    | \.venv
    | venv
    | env
    | build
    | dist
    | .*/(bin|lib|share|etc)
    | .*/pyvenv\.cfg
)/
'''

[tool.ruff]
target-version = "py312"
exclude = [
    "__pycache__",
    "*.pyc",
    ".uv-cache",
    ".venv",
    "venv",
    "env",
    "*/bin/**",
    "*/lib/**",
    "*/share/**",
    "*/etc/**",
    "*/pyvenv.cfg"
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

