---
- name: "Find Homebrew prefix"
  ansible.builtin.command:
    cmd: "brew --prefix"
  register: bun_homebrew_prefix
  changed_when: false

- name: "Set Homebrew binary path"
  ansible.builtin.set_fact:
    bun_homebrew_bin_path: "{{ bun_homebrew_prefix.stdout }}/bin"

- name: "Install Bun"
  community.general.homebrew:
    name: bun
    state: present

- name: "Verify Bun version"
  ansible.builtin.command:
    cmd: "bun --version"
  register: bun_version_check
  changed_when: false
  environment:
    PATH: "{{ bun_homebrew_bin_path }}:{{ ansible_facts['env']['PATH'] }}"

- name: "Verify Bun revision"
  ansible.builtin.command:
    cmd: "bun --revision"
  register: bun_revision_check
  changed_when: false
  environment:
    PATH: "{{ bun_homebrew_bin_path }}:{{ ansible_facts['env']['PATH'] }}"
