---
- name: "Install Visual Studio Code"
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present

- name: "Ensure VS Code User directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/Code/User"
    state: directory
    mode: '0755'

- name: "Find VS Code config files"
  ansible.builtin.find:
    paths: "{{ config_dir_abs_path }}/editor/vscode"
    patterns: "*.json"
    recurse: true
  register: vscode_files

- name: "Symlink VS Code config files"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ vscode_files.files }}"

- name: "Read VS Code extensions list"
  ansible.builtin.slurp:
    src: "{{ config_dir_abs_path }}/editor/vscode/extensions.json"
  register: vscode_extensions_content

- name: "Parse VS Code extensions JSON"
  ansible.builtin.set_fact:
    vscode_extensions: "{{ (vscode_extensions_content.content | b64decode | from_json).extensions }}"

- name: "Install VS Code extensions"
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  ignore_errors: true
  register: install_result
  changed_when: "'was successfully installed' in install_result.stdout"