---
- name: "Install and configure Claude"
  ansible.builtin.import_tasks: claude.yml
  tags: [claude]

- name: "Install and configure Gemini"
  ansible.builtin.import_tasks: gemini.yml
  tags: [gemini]

- name: "Install and configure Codex"
  ansible.builtin.import_tasks: codex.yml
  tags: [codex]
