---
# Shows or hides icons for external hard drives on the desktop.
- key: ShowExternalHardDrivesOnDesktop
  domain: com.apple.finder
  type: bool
  default: true
  comment: "Desktop"

# Enables or disables the "Click wallpaper to reveal desktop" feature.
- key: EnableStandardClickToShowDesktop
  domain: com.apple.WindowManager
  type: bool
  default: true
