---
# Sets the default location for saving screenshots.
- key: location
  domain: com.apple.screencapture
  type: string
  default: "$HOME/Desktop"
  comment: "Screenshots"

# Disables the shadow effect for window screenshots.
- key: disable-shadow
  domain: com.apple.screencapture
  type: bool
  default: false

# Includes the date in the screenshot filename.
- key: include-date
  domain: com.apple.screencapture
  type: bool
  default: false

# Shows a thumbnail of the screenshot after taking it.
- key: show-thumbnail
  domain: com.apple.screencapture
  type: bool
  default: true

# Sets the default file format for screenshots (e.g., png, jpg, gif, tiff, bmp).
- key: type
  domain: com.apple.screencapture
  type: string
  default: "png"