---
- name: "Install rustup-init via Homebrew"
  community.general.homebrew:
    name: "rustup-init"
    state: present

- name: "Bootstrap rustup with minimal stable toolchain"
  ansible.builtin.command:
    cmd: "rustup-init -y --no-modify-path --profile minimal --default-toolchain stable"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: "Install stable toolchain via rustup"
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup toolchain install stable --profile minimal"
  changed_when: false
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: "Ensure Rust components are available"
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup component add {{ item }}"
  loop:
    - rustfmt
    - clippy
  changed_when: false
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"
