---
- name: "Load Rust tools definition from Git"
  ansible.builtin.include_vars:
    file: "{{ role_path }}/config/common/rust-tools.yml"
    name: rust_git_tools

- name: "Install Rust CLI tools from GitHub"
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo install --git {{ item.repo }} --tag {{ item.tag }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.name }}"
  loop: "{{ rust_git_tools }}"
  loop_control:
    loop_var: item
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"
  changed_when: false
