---
- name: "Verify VS Code command is available"
  ansible.builtin.command:
    cmd: "which code"
  changed_when: false

- name: "Ensure VS Code User directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Code/User"
    state: directory
    mode: "0755"

- name: "Symlink VS Code shared config files"
  ansible.builtin.file:
    src: "{{ local_config_root }}/editor/global/vscode/{{ item }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Code/User/{{ item }}"
    state: link
    force: true
  loop:
    - settings.json
    - keybindings.json

- name: "Read VS Code extensions list"
  ansible.builtin.slurp:
    src: "{{ local_config_root }}/editor/global/vscode/extensions.json"
  register: editor_vscode_extensions_content

- name: "Parse VS Code extensions JSON"
  ansible.builtin.set_fact:
    editor_vscode_extensions: "{{ (editor_vscode_extensions_content.content | b64decode | from_json).extensions }}"

- name: "Read installed VS Code extensions"
  ansible.builtin.command: "code --list-extensions"
  register: editor_vscode_installed_extensions
  changed_when: false

- name: "Install VS Code extensions"
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ editor_vscode_extensions }}"
  when: item | lower not in editor_vscode_installed_extensions.stdout_lines | map('lower') | list
  changed_when: true
