---
- name: Ensure .ssh directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Ensure .ssh/conf.d directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/conf.d"
    state: directory
    mode: '0700'

- name: Symlink main ssh config file
  ansible.builtin.file:
    src: "{{ repo_root_path }}/config/common/ssh/config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    state: link
    force: yes

- name: Symlink individual ssh config files
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/conf.d/{{ item | basename }}"
    state: link
    force: yes
  with_fileglob:
    - "{{ repo_root_path }}/config/common/ssh/conf.d/*.conf"