---
services_mac_mini_ollama_service_port: 11435
services_mac_mini_ollama_context_length: 4096
services_mac_mini_ollama_max_loaded_models: 1
services_mac_mini_ollama_num_parallel: 1
services_mac_mini_ollama_max_queue: 512
services_mac_mini_ollama_flash_attention: true
services_mac_mini_ollama_keep_alive: 10m
services_mac_mini_ollama_gpu_overhead: 1024
services_mac_mini_ollama_kv_cache_type: q8_0
services_mac_mini_mlx_service_port: 8081
services_mac_mini_mlx_model: "mlx-community/Llama-3.2-3B-Instruct-4bit"
services_mac_mini_nexus_backend: "ollama"
services_mac_mini_nexus_timeout: 60
services_mac_mini_nexus_ollama_model: "llama3.2:3b"
services_mac_mini_nexus_internal_url: "http://nexus:8000"
services_mac_mini_nexus_image: "ghcr.io/asterismhq/nexus:latest"
services_mac_mini_starprobe_image: "ghcr.io/asterismhq/starprobe:latest"
services_mac_mini_obs_glx_api_image: "ghcr.io/asterismhq/obs-glx:latest"
services_mac_mini_obs_glx_worker_image: "ghcr.io/asterismhq/obs-glx/obs-glx-worker:latest"
services_mac_mini_postgres_image: "postgres:16-alpine"
services_mac_mini_redis_image: "redis:7-alpine"
services_mac_mini_nexus_host_port: 18000
services_mac_mini_starprobe_host_port: 18001
services_mac_mini_obs_glx_host_port: 18002
services_mac_mini_postgres_host_port: 15432
services_mac_mini_redis_host_port: 16379
services_mac_mini_starprobe_backend: "ollama"
services_mac_mini_starprobe_use_mock_nexus: false
services_mac_mini_starprobe_use_mock_search: false
services_mac_mini_starprobe_use_mock_scraping: false
services_mac_mini_starprobe_internal_url: "http://starprobe:8000/research"
services_mac_mini_postgres_db: "obs-glx"
services_mac_mini_postgres_user: "obs_glx"
services_mac_mini_postgres_password: "obs_glx_password"
services_mac_mini_postgres_volume: "mac-mini-postgres-data"
services_mac_mini_obs_glx_tmp_volume: "mac-mini-obs-glx-tmp"
services_mac_mini_obs_glx_project_name: "obs-glx"
services_mac_mini_obs_glx_use_mock_starprobe: false
services_mac_mini_obs_glx_use_mock_github: true
services_mac_mini_obs_glx_use_mock_nexus: false
services_mac_mini_obs_glx_token: ""
