---
- name: "Ensure .aider directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.aider"
    state: directory
    mode: "0755"

- name: "Symlink aider config files"
  ansible.builtin.file:
    src: "{{ role_path }}/config/common/aider/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: true
  loop:
    - .aider.conf.yml
    - .aider.model.settings.yml
