---
- name: "Deploy all services for mac-mini"
  community.docker.docker_compose_v2:
    project_src: "{{ repo_root_path }}/ansible/services/mac-mini/compose/"
    state: present
    restarted: true

- name: "Wait for stub-api service to become available"
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 8080
    timeout: 60
