name: Setup Base Environment
description: Install Python, uv, and Ansible dependencies

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create .env file
      shell: bash
      run: cp .env.example .env

    - name: Setup just
      uses: extractions/setup-just@v2

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install Ansible and dependencies with uv
      shell: bash
      run: uv sync --frozen
