---
tools:
  codex:
    skills_dir: "{{ ansible_facts['env']['HOME'] }}/.codex/skills"
  claude:
    skills_dir: "{{ ansible_facts['env']['HOME'] }}/.claude/skills"
  antigravity_ide:
    skills_dir: "{{ ansible_facts['env']['HOME'] }}/.config/google/antigravity/skills"
