"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

# User configuration will be set via environment variables
# using 'jj config set --user user.name' and 'jj config set --user user.email'

[ui]
color = "auto"
editor = "code --wait"
diff-editor = "code --wait --diff"