---
- name: "Find Homebrew prefix"
  ansible.builtin.command:
    cmd: "brew --prefix"
  register: go_homebrew_prefix
  changed_when: false

- name: "Set Homebrew binary path"
  ansible.builtin.set_fact:
    go_homebrew_bin_path: "{{ go_homebrew_prefix.stdout }}/bin"

- name: "Set Go environment root"
  ansible.builtin.set_fact:
    go_environment_root: "{{ ansible_facts['env']['HOME'] }}/.goenv"

- name: "Set Go command path"
  ansible.builtin.set_fact:
    go_command_path: "{{ go_environment_root }}/shims:{{ go_environment_root }}/bin:{{ go_homebrew_bin_path }}:{{ ansible_facts['env']['PATH'] }}"

- name: "Install specified Go version with goenv"
  ansible.builtin.command:
    cmd: "goenv install {{ go_version }} --skip-existing"
  args:
    creates: "{{ go_environment_root }}/versions/{{ go_version }}"
  changed_when: false
  environment:
    PATH: "{{ go_command_path }}"
    GOENV_ROOT: "{{ go_environment_root }}"

- name: "Get current global Go version"
  ansible.builtin.command:
    cmd: "goenv global"
  register: go_current_global
  changed_when: false
  environment:
    PATH: "{{ go_command_path }}"
    GOENV_ROOT: "{{ go_environment_root }}"

- name: "Set global Go version"
  ansible.builtin.command:
    cmd: "goenv global {{ go_version }}"
  changed_when: "go_current_global.stdout | trim != go_version"
  environment:
    PATH: "{{ go_command_path }}"
    GOENV_ROOT: "{{ go_environment_root }}"

- name: "Rehash goenv shims"
  ansible.builtin.command:
    cmd: "goenv rehash"
  changed_when: false
  environment:
    PATH: "{{ go_command_path }}"
    GOENV_ROOT: "{{ go_environment_root }}"
