- name: Ensure Codex directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env.HOME }}/.codex"
    - "{{ ansible_env.HOME }}/.codex/prompts"
  tags: codex

- name: Symlink Codex configuration file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/config/common/aiding/codex/config.toml"
    dest: "{{ ansible_env.HOME }}/.codex/config.toml"
    state: link
    force: yes
  tags: codex
