---
- name: "Read Node.js version"
  ansible.builtin.import_tasks: version.yml
  tags: [nodejs, nodejs-platform, nodejs-tools]

- name: "Setup Node.js platform"
  ansible.builtin.import_tasks: platform.yml
  tags: [nodejs-platform]

- name: "Install Node.js tools and packages"
  ansible.builtin.import_tasks: tools.yml
  tags: [nodejs-tools]
