---
- name: "Set Node.js version variable from file"
  ansible.builtin.slurp:
    src: "{{ role_path }}/config/common/.nvmrc"
  register: nodejs_version_file

- name: "Set Node.js version fact"
  ansible.builtin.set_fact:
    nodejs_version: "{{ nodejs_version_file.content | b64decode | trim }}"

- name: "Setup Node.js platform"
  ansible.builtin.include_tasks: platform.yml
  when: "'nodejs-platform' in ansible_run_tags"

- name: "Install Node.js tools and packages"
  ansible.builtin.include_tasks: tools.yml
  when: "'nodejs-tools' in ansible_run_tags"

- name: "Install and configure Claude"
  ansible.builtin.include_tasks: claude.yml
  when: "'claude' in ansible_run_tags"

- name: "Install and configure Gemini"
  ansible.builtin.include_tasks: gemini.yml
  when: "'gemini' in ansible_run_tags"

- name: "Install and configure Codex"
  ansible.builtin.include_tasks: codex.yml
  when: "'codex' in ansible_run_tags"
