---
- name: "Set Node.js version variable from file"
  ansible.builtin.slurp:
    src: "{{ role_path }}/config/common/.nvmrc"
  register: nodejs_version_file

- name: "Set Node.js version fact"
  ansible.builtin.set_fact:
    nodejs_version: "{{ nodejs_version_file.content | b64decode | trim }}"

- name: "Install nvm, jq, and pnpm"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - nvm
    - jq
    - pnpm

- name: "Install specified Node.js version with nvm"
  ansible.builtin.shell:
    cmd: "source $(brew --prefix nvm)/nvm.sh && nvm install {{ nodejs_version }} --skip-existing"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ nodejs_version }}"
  changed_when: false
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"

- name: "Set default Node.js version"
  ansible.builtin.shell:
    cmd: "source $(brew --prefix nvm)/nvm.sh && nvm alias default {{ nodejs_version }}"
  changed_when: false
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
