---
- name: "Set Node.js version variable from file"
  ansible.builtin.slurp:
    src: "{{ config_dir_abs_path }}/runtime/nodejs/.nvmrc"
  register: nodejs_version_file

- name: "Set Node.js version fact"
  ansible.builtin.set_fact:
    nodejs_version: "{{ nodejs_version_file.content | b64decode | trim }}"
