---
- name: "Check if pipx is installed"
  ansible.builtin.command: "command -v pipx"
  register: python_pipx_check
  ignore_errors: true
  changed_when: false
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/shims:{{ ansible_env.PATH }}"

- name: "Install pipx using pyenv Python"
  ansible.builtin.shell: |
    eval "$(pyenv init -)"
    pyenv shell {{ python_version }}
    python -m pip install --user pipx
    python -m pipx ensurepath
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/shims:{{ ansible_env.PATH }}"
  when: python_pipx_check.rc != 0
  changed_when: python_pipx_check.rc != 0

- name: "Install aider-chat with pipx using specific Python version"
  community.general.pipx:
    name: aider-chat
    python: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python_version }}/bin/python"
    state: present
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.HOME }}/.pyenv/shims:{{ ansible_env.PATH }}"

- name: "Ensure .aider directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.aider"
    state: directory
    mode: "0755"

- name: "Symlink aider config files"
  ansible.builtin.file:
    src: "{{ role_path }}/config/common/aider/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: true
  loop:
    - .aider.conf.yml
    - .aider.model.settings.yml
