---
- name: "Install uv with pipx"
  community.general.pipx:
    name: uv
    state: present
    executable: /opt/homebrew/bin/pipx

- name: "Ensure .config/uv directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/uv"
    state: directory
    mode: "0755"

- name: "Symlink uv.toml"
  ansible.builtin.file:
    src: "{{ role_path }}/config/common/uv.toml"
    dest: "{{ ansible_env.HOME }}/.config/uv/uv.toml"
    state: link
    force: true
