version: "3.8"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - "~/.ollama/models:/root/.ollama/models"
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=-1
