---
- name: "Find Homebrew prefix"
  ansible.builtin.command:
    cmd: "brew --prefix"
  register: python_homebrew_prefix
  changed_when: false

- name: "Set Homebrew binary path"
  ansible.builtin.set_fact:
    python_homebrew_bin_path: "{{ python_homebrew_prefix.stdout }}/bin"

- name: "Install uv"
  community.general.homebrew:
    name: uv
    state: present

- name: "Ensure .config/uv directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/uv"
    state: directory
    mode: "0755"

- name: "Symlink uv.toml"
  ansible.builtin.file:
    src: "{{ local_config_root }}/python/global/uv.toml"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/uv/uv.toml"
    state: link
    force: true

- name: "Install uv-managed Python version"
  ansible.builtin.command:
    cmd: "uv python install {{ python_version }} --default --no-progress"
  register: python_uv_install
  changed_when: "'Installed Python' in python_uv_install.stderr"
  environment:
    PATH: "{{ python_homebrew_bin_path }}:{{ ansible_facts['env']['PATH'] }}"
