---
# Sets the mouse tracking speed. A higher value means faster tracking.
- key: com.apple.mouse.scaling
  domain: .GlobalPreferences
  type: float
  default: 1
  comment: "Mouse"

# Makes the window under the cursor active in Terminal.
- key: FocusFollowsMouse
  domain: com.apple.Terminal
  type: bool
  default: true