---
- key: com.apple.sound.uiaudio.enabled
  domain: com.apple.systemsound
  type: int
  default: 0
  comment: "Sound"

- key: com.apple.sound.beep.feedback
  domain: NSGlobalDomain
  type: int
  default: 0

- key: com.apple.sound.beep.sound
  domain: NSGlobalDomain
  type: string
  default: "/System/Library/Sounds/Boop.aiff"

- key: "Apple Bitpool Min (editable)"
  domain: com.apple.BluetoothAudioAgent
  type: int
  default: 40