# Use Copy-on-Write for efficient and safe file linking on macOS.
link-mode = "clone"

# Allow pre-releases only when necessary or explicitly requested.
prerelease = "if-necessary-or-explicit"

# Always resolve to the highest compatible version of packages.
resolution = "highest"

# Specify the cache directory.
cache-dir = "~/.cache/uv"

# Set the number of concurrent downloads.
concurrent-downloads = 50