---
# Docker setup and validation tasks

- name: Read Docker images list
  slurp:
    src: "{{ config_dir_abs_path }}/docker/images.txt"
  register: images_file

- name: Set images list
  set_fact:
    docker_images: "{{ images_file.content | b64decode | split('\n') | select | list }}"

- name: Pull Docker images
  command: docker pull {{ item }}
  register: pull_result
  changed_when: false
  loop: "{{ docker_images }}"

- name: Display pull results
  debug:
    msg: "Pulling {{ item.item }}... {{ '✅ pulled' if item.rc == 0 else '❌ failed' }}"
  loop: "{{ pull_result.results | default([]) }}"

- name: Confirm Docker images are available
  shell: docker images --format {% raw %}'table {{.Repository}}:{{.Tag}}'{% endraw %}
  register: docker_images_list
  changed_when: false

- name: Display available Docker images
  debug:
    msg: "{{ docker_images_list.stdout }}"