---
- hosts: localhost
  connection: local

  vars:
    # This 'config_dir' variable is passed from the justfile
    config_dir_abs_path: "{{ config_dir_abs_path }}"

  roles:
    - { role: brew, tags: ['brew'] }
    - { role: java, tags: ['java'] }
    - { role: python, tags: ['python'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: git, tags: ['git', 'gh'] }
    - { role: shell, tags: ['shell'] }
    - { role: vscode, tags: ['vscode'] }
    - { role: system_defaults, tags: ['system_defaults'] }