---
- name: Setup macOS development environment
  hosts: localhost
  connection: local
  roles:
    - { role: brew, tags: ["brew", "brew-formulae", "brew-cask"] }
    - { role: python, tags: ["python-platform", "python-tools", "aider", "uv"] }
    - { role: nodejs, tags: ["nodejs-platform", "nodejs-tools", "claude", "gemini", "codex"] }
    - { role: slash, tags: ["slash"] }
    - { role: ruby, tags: ["ruby"] }
    - { role: vcs, tags: ["git", "jj"] }
    - { role: gh, tags: ["gh"] }
    - { role: shell, tags: ["shell"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: editor, tags: ["editor", "vscode", "cursor"] }
    - { role: coderabbit, tags: ["coderabbit"] }
    - { role: mcp, tags: ["mcp"] }
    - { role: system, tags: ["system"] }
    - { role: docker, tags: ["docker"] }
    - { role: services, tags: ["services"] }
