---
- hosts: localhost
  connection: local

  vars:
    # This 'config_dir' variable is passed from the justfile
    config_dir_abs_path: "{{ config_dir_abs_path }}"

  roles:
    - { role: brew, tags: ['brew'] }
    - { role: python, tags: ['python'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: claude, tags: ['claude'] }
    - { role: gemini, tags: ['gemini'] }
    - { role: codex, tags: ['codex'] }
    - { role: slash, tags: ['slash'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: vcs, tags: ['vcs'] }
    - { role: gh, tags: ['gh'] }
    - { role: shell, tags: ['shell'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: vscode, tags: ['editor', 'vscode'] }
    - { role: cursor, tags: ['editor', 'cursor'] }
    - { role: mcp, tags: ['mcp'] }
    - { role: system, tags: ['system'] }
    - { role: docker, tags: ['docker'] }
