---
- name: "Ensure slash generator scripts are executable"
  ansible.builtin.file:
    path: "{{ role_path }}/config/common/{{ item }}"
    mode: "0755"
  loop:
    - claude.sh
    - gemini.sh
    - codex.sh

- name: "Regenerate slash commands"
  ansible.builtin.command:
    argv:
      - "{{ role_path }}/config/common/{{ item }}"
  args:
    chdir: "{{ repo_root_path }}"
  loop:
    - claude.sh
    - gemini.sh
    - codex.sh
  changed_when: false
  loop_control:
    label: "{{ item }}"
