---
- name: "Ensure slash generator scripts are executable"
  ansible.builtin.file:
    path: "{{ config_dir_abs_path }}/aiding/slash/{{ item }}"
    mode: '0755'
  loop:
    - claude.sh
    - gemini.sh
    - codex.sh

- name: "Regenerate slash commands"
  ansible.builtin.command:
    argv:
      - "{{ config_dir_abs_path }}/aiding/slash/{{ item }}"
  args:
    chdir: "{{ repo_root_path }}"
  loop:
    - claude.sh
    - gemini.sh
    - codex.sh
  loop_control:
    label: "{{ item }}"
