---
# Generate Claude Code and Gemini CLI slash commands from unified config

- name: Check if Claude commands directory exists
  stat:
    path: "{{ ansible_env.HOME }}/.claude/commands"
  register: claude_commands_dir

- name: Check if Gemini commands directory exists
  stat:
    path: "{{ ansible_env.HOME }}/.gemini/commands"
  register: gemini_commands_dir

- name: Generate Claude Code slash commands
  shell: "{{ config_dir_abs_path }}/slash/claude.sh"
  args:
    chdir: "{{ config_dir_abs_path | dirname | dirname }}"
  when: claude_commands_dir.stat.exists
  tags:
    - slash
    - claude

- name: Generate Gemini CLI slash commands
  shell: "{{ config_dir_abs_path }}/slash/gemini.sh"
  args:
    chdir: "{{ config_dir_abs_path | dirname | dirname }}"
  when: gemini_commands_dir.stat.exists
  tags:
    - slash
    - gemini

- name: Display completion message for Claude commands
  debug:
    msg: "✅ Claude Code slash commands generated successfully"
  when: claude_commands_dir.stat.exists

- name: Display completion message for Gemini commands
  debug:
    msg: "✅ Gemini CLI slash commands generated successfully"
  when: gemini_commands_dir.stat.exists

- name: Skip message for missing Claude directory
  debug:
    msg: "⏭️ Skipping Claude commands generation - ~/.claude/commands directory not found"
  when: not claude_commands_dir.stat.exists

- name: Skip message for missing Gemini directory
  debug:
    msg: "⏭️ Skipping Gemini commands generation - ~/.gemini/commands directory not found"
  when: not gemini_commands_dir.stat.exists