---
- name: "Ensure slash generator scripts are executable"
  ansible.builtin.file:
    path: "{{ repo_root_path }}/ansible/scripts/slash/{{ item }}"
    mode: "0755"
  loop:
    - claude.py
    - gemini.py
    - codex.py

- name: "Regenerate slash commands"
  ansible.builtin.command:
    argv:
      - "{{ repo_root_path }}/ansible/scripts/slash/{{ item }}"
  args:
    chdir: "{{ repo_root_path }}"
  loop:
    - claude.py
    - gemini.py
    - codex.py
  changed_when: false
  loop_control:
    label: "{{ item }}"

- name: "Ensure ~/.local/slash directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/slash"
    state: directory
    mode: "0755"

- name: "Symlink slash command prompts directory"
  ansible.builtin.file:
    src: "{{ role_path }}/config/common/commands"
    dest: "{{ ansible_env.HOME }}/.local/slash/commands"
    state: link
    force: true
