---
- name: "Reject non-macOS hosts"
  ansible.builtin.assert:
    that:
      - ansible_facts['system'] == 'Darwin'
    fail_msg: >-
      nodejs role supports macOS only. Current platform is
      {{ ansible_facts['system'] }}.

- name: "Find Homebrew prefix"
  ansible.builtin.command:
    cmd: "brew --prefix"
  register: nodejs_homebrew_prefix
  changed_when: false

- name: "Set Homebrew binary path"
  ansible.builtin.set_fact:
    nodejs_homebrew_bin_path: "{{ nodejs_homebrew_prefix.stdout }}/bin"

- name: "Set Node.js version variable from file"
  ansible.builtin.slurp:
    src: "{{ local_config_root }}/nodejs/global/.node-version"
  register: nodejs_version_file

- name: "Set Node.js version fact"
  ansible.builtin.set_fact:
    nodejs_version: "{{ nodejs_version_file.content | b64decode | trim }}"

- name: "Symlink npm global config"
  ansible.builtin.file:
    src: "{{ local_config_root }}/nodejs/global/.npmrc"
    dest: "{{ ansible_facts['env']['HOME'] }}/.npmrc"
    state: link
    force: true

- name: "Install specified Node.js version with fnm"
  ansible.builtin.command:
    cmd: "fnm install {{ nodejs_version }} --progress=never"
  register: nodejs_fnm_install
  changed_when: "'already installed' not in (nodejs_fnm_install.stdout ~ nodejs_fnm_install.stderr)"
  environment:
    PATH: "{{ nodejs_homebrew_bin_path }}:{{ ansible_facts['env']['PATH'] }}"

- name: "Set default Node.js version"
  ansible.builtin.command:
    cmd: "fnm default {{ nodejs_version }}"
  changed_when: false
  environment:
    PATH: "{{ nodejs_homebrew_bin_path }}:{{ ansible_facts['env']['PATH'] }}"
