name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-homebrew:
    uses: ./.github/workflows/setup-homebrew.yml
    secrets: inherit

  setup-installers:
    uses: ./.github/workflows/setup-installers.yml

  setup-python:
    uses: ./.github/workflows/setup-python.yml

  setup-node:
    uses: ./.github/workflows/setup-node.yml

  setup-shell:
    uses: ./.github/workflows/setup-shell.yml

  setup-system-defaults:
    uses: ./.github/workflows/setup-system-defaults.yml

