name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-python:
    uses: ./.github/workflows/setup-python.yml

  setup-nodejs:
    uses: ./.github/workflows/setup-nodejs.yml

  setup-sublang:
    uses: ./.github/workflows/setup-sublang.yml

  setup-vcs:
    uses: ./.github/workflows/setup-vcs.yml

  setup-ide:
    uses: ./.github/workflows/setup-ide.yml

  setup-homebrew:
    uses: ./.github/workflows/setup-homebrew.yml
    secrets: inherit

  setup-alias:
    uses: ./.github/workflows/setup-alias.yml

  setup-system:
    uses: ./.github/workflows/setup-system.yml

