name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-python:
    uses: ./.github/workflows/setup-python.yml

  setup-nodejs:
    uses: ./.github/workflows/setup-nodejs.yml

  setup-components:
    uses: ./.github/workflows/setup-components.yml

  setup-vscode:
    uses: ./.github/workflows/setup-vscode.yml

  setup-gh:
    uses: ./.github/workflows/setup-gh.yml
    secrets: inherit

  setup-homebrew:
    uses: ./.github/workflows/setup-homebrew.yml
    secrets: inherit

  setup-system:
    uses: ./.github/workflows/setup-system.yml

