name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-components:
    uses: ./.github/workflows/setup-components.yml

  setup-homebrew:
    uses: ./.github/workflows/setup-homebrew.yml
    secrets: inherit

  setup-system-defaults:
    uses: ./.github/workflows/setup-system-defaults.yml

