name: MacOS Environment Setup CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test:
    name: Run Setup Testss
    uses: ./.github/workflows/run-setup-test.yml
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Completion
    if: github.event_name == 'pull_request' && always()
    needs: [test]
    permissions:
      pull-requests: write 
    uses: ./.github/workflows/notify-completion.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      macos_test_result: ${{ needs.test.result }}
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}