name: MacOS Environment Setup CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-test:
    name: Run Setup Tests
    uses: ./.github/workflows/run-setup-test.yml
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}