name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-homebrew:
    uses: ./.github/workflows/setup-homebrew.yml
    secrets: inherit

  setup-git:
    uses: ./.github/workflows/setup-git.yml

  setup-node:
    uses: ./.github/workflows/setup-node.yml

  setup-ruby:
    uses: ./.github/workflows/setup-ruby.yml

  setup-python:
    uses: ./.github/workflows/setup-python.yml

  setup-flutter:
    uses: ./.github/workflows/setup-flutter.yml

  setup-cursor:
    uses: ./.github/workflows/setup-cursor.yml

  setup-vscode:
    uses: ./.github/workflows/setup-vscode.yml

  setup-macos:
    uses: ./.github/workflows/setup-macos.yml

  setup-shell:
    uses: ./.github/workflows/setup-shell.yml

  setup-java:
    uses: ./.github/workflows/setup-java.yml

  verify-macos-backup-script:
    name: Verify Backup Script
    uses: ./.github/workflows/verify-macos-backup-script.yml
