name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-homebrew:
    uses: ./.github/workflows/setup-homebrew.yml
    secrets: inherit

  setup-installers:
    uses: ./.github/workflows/setup-installers.yml

  setup-macos:
    uses: ./.github/workflows/setup-macos.yml

