name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-setup-tests:
    name: Run Setup Tests
    uses: ./.github/workflows/setup-test.yml

  verify-macos-backup-script:
    name: Verify Backup Script
    uses: ./.github/workflows/verify-macos-backup-script.yml
