name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-platform-tools:
    uses: ./.github/workflows/setup-platform-tools.yml

  setup-components:
    uses: ./.github/workflows/setup-components.yml

  setup-gh:
    uses: ./.github/workflows/setup-gh.yml
    secrets: inherit

  setup-homebrew:
    uses: ./.github/workflows/setup-homebrew.yml
    secrets: inherit

  setup-system-defaults:
    uses: ./.github/workflows/setup-system-defaults.yml

