name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  setup-python:
    uses: ./.github/workflows/setup-python.yml

  setup-nodejs:
    uses: ./.github/workflows/setup-nodejs.yml

  setup-ruby:
    uses: ./.github/workflows/setup-ruby.yml

  setup-ide:
    uses: ./.github/workflows/setup-ide.yml

  setup-system:
    uses: ./.github/workflows/setup-system.yml
