name: macOS環境構築のCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  code-review:
    name: Code Review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  test-install:
    name: Install and Test
    runs-on: macos-latest
    timeout-minutes: 120
    
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      
      - name: GitHub認証の設定
        run: |
          # GitHubの認証を設定 (CI環境用)
          git config --global url."https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          echo "✅ CI環境用のGitHub認証を設定しました"
      
      - name: スクリプトに実行権限を付与
        run: |
          chmod +x .github/workflows/setup_test.sh
          chmod +x .github/workflows/verify_environment.sh
          echo "✅ テストスクリプトに実行権限を付与しました"
      
      - name: macOS環境セットアップテストの実行
        run: .github/workflows/setup_test.sh all
        env:
          CI: true
          GITHUB_TOKEN_CI: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}