name: Collect Coverage

on:
  workflow_call:

jobs:
  coverage:
    name: Run test coverage
    runs-on: macos-14
    env:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Install cargo-tarpaulin
        run: cargo install --locked cargo-tarpaulin --version 0.35.2

      - name: Generate coverage
        continue-on-error: true
        run: mise exec -- just coverage
