name: Lint and Test

on:
  workflow_call:

jobs:
  lint-and-test:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Create mlx-lm venv
        run: uv venv mlx-lm

      - name: Install mlx dependencies
        env:
          UV_PROJECT_ENVIRONMENT: ./mlx-lm
        run: uv sync --only-group mlx
        
      - name: Run tests
        run: just test

      - name: Run Linters
        run: just lint
