name: Test and Lint

on:
  workflow_call:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run Linters
        run: just lint

      - name: Run tests
        run: just test