name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run Rust tests
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - name: Run tests
        run: mise exec -- just test
