name: Setup Components

on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-15
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        component:
          - git
          - ruby
          - java
          - cursor
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Setup ${{ matrix.component }}
        run: just cmn-${{ matrix.component }}