name: Setup Node.js and LLM Tools

on:
  workflow_call:

jobs:
  setup-nodejs:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Run nodejs-platform setup
        run: just nodejs-platform

      - name: Run nodejs-tools setup
        run: just nodejs-tools

      - name: Setup Claude Code
        run: just claude

      - name: Setup Gemini CLI
        run: just gemini

      - name: Setup Codex
        run: just codex

      - name: Setup slash commands
        run: just slash
