name: Setup IDE

on:
  workflow_call:

jobs:
  setup-ide:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - name: Setup Ansible environment
        uses: ./.github/actions/setup-ansible

      - name: Setup VSCode configuration
        run: mise exec -- just run make vscode

      - name: Setup Antigravity configuration
        run: mise exec -- just run make antigravity

      - name: Setup Zed configuration
        run: mise exec -- just run make zed

      - name: Setup Xcode configuration
        run: mise exec -- just run make xcode
