name: Setup IDE

on:
  workflow_call:

jobs:
  setup-vscode:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Setup VSCode configuration
        run: just cmn-vscode

      - name: Setup Cursor configuration
        run: just cmn-cursor

      - name: Setup CodeRabbit CLI
        run: just cmn-coderabbit