name: Setup IDE

on:
  workflow_call:

jobs:
  setup-vscode:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Setup VSCode configuration
        run: just cmn-vscode

      - name: Test VSCode extensions backup script
        run: |
          set -euo pipefail
          just cmn-backup-vscode-extensions
          git diff --quiet --exit-code -- config/common/vscode/extensions.json || { echo "❌ extensions.json が未コミット/未同期です。'just cmn-backup-vscode-extensions' 実行後に変更をコミットしてください。"; exit 1; }

      - name: Setup Cursor configuration
        run: just cmn-cursor