name: Setup macOS and Shell

on:
  workflow_call:

jobs:
  setup-macos:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create symbolic links for shell configuration
        run: make link-shell

      - name: Apply macOS system settings
        run: make apply-settings

      - name: Re-run backup to check for idempotency
        run: make backup-settings

      - name: Verify that settings file is unchanged
        run: |
          git diff --exit-code -- macos/config/settings/macos-settings.sh
