name: Setup Homebrew Formulae

on:
  workflow_call:

jobs:
  setup-homebrew:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Setup GitHub authentication for Homebrew
        run: |
          echo "🔑 CI環境用のGitHub認証を設定中..."
          # 認証情報を環境変数に設定
          echo "HOMEBREW_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          # Gitの認証設定
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}"
          echo "✅ GitHub認証の設定が完了しました"
        shell: bash

      - name: Run Homebrew formulae setup for common
        run: just cmn-formulae


