name: Setup IDE

on:
  workflow_call:

permissions:
  contents: read

jobs:
  setup-ide:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - name: Setup Ansible environment
        uses: ./.github/actions/setup-ansible

      - name: Setup VSCode configuration
        run: mise exec -- just run make vscode

      - name: Setup Antigravity configuration
        run: mise exec -- just run make antigravity

      - name: Setup Zed configuration
        run: mise exec -- just run make zed

      - name: Setup Xcode configuration
        run: mise exec -- just run make xcode
