name: Setup Ruby

on:
  workflow_call:

jobs:
  setup-ruby:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - name: Setup Ansible environment
        uses: ./.github/actions/setup-ansible

      - name: Setup ruby
        run: mise exec -- just run make ruby
