name: Setup macOS and Shell

on:
  workflow_call:

jobs:
  setup-macos:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create symbolic links for shell configuration
        run: make link-shell

      - name: Apply macOS system defaults
        run: make apply-defaults

      - name: Re-run backup to check for idempotency
        run: make backup-defaults

      - name: Verify that system defaults file is unchanged
        run: |
          git diff --exit-code -- macos/config/system-defaults/system-defaults.sh
