name: Setup Platform-based Tools

on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        component:
          - python
          - node
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ${{ matrix.component }}-platform setup
        run: make ${{ matrix.component }}-platform

      - name: Run ${{ matrix.component }}-tools setup
        run: make ${{ matrix.component }}-tools

      - name: Run ${{ matrix.component }}-platform setup for idempotency check
        id: idempotency-platform
        run: |
          set -o pipefail
          delim="EOF$(date +%s%N)"
          # Re-run and capture stderr and exit code
          stderr_output=$( (make ${{ matrix.component }}-platform >/dev/null) 2>&1 ); exit_code=$?
          {
            echo "stderr_output<<${delim}"
            echo "${stderr_output}"
            echo "${delim}"
            echo "exit_code=${exit_code}"
          } >> "${GITHUB_OUTPUT}"

      - name: Verify idempotency for ${{ matrix.component }}-platform
        if: steps.idempotency-platform.outputs.exit_code != '0' || contains(steps.idempotency-platform.outputs.stderr_output, 'IDEMPOTENCY_VIOLATION')
        run: |
          echo "Idempotency check failed for ${{ matrix.component }}-platform"
          echo "Error output:"
          echo "${{ steps.idempotency-platform.outputs.stderr_output }}"
          echo "Exit code: ${{ steps.idempotency-platform.outputs.exit_code }}"
          exit 1

      - name: Run ${{ matrix.component }}-tools setup for idempotency check
        id: idempotency-tools
        run: |
          set -o pipefail
          delim="EOF$(date +%s%N)"
          # Re-run and capture stderr and exit code
          stderr_output=$( (make ${{ matrix.component }}-tools >/dev/null) 2>&1 ); exit_code=$?
          {
            echo "stderr_output<<${delim}"
            echo "${stderr_output}"
            echo "${delim}"
            echo "exit_code=${exit_code}"
          } >> "${GITHUB_OUTPUT}"

      - name: Verify idempotency for ${{ matrix.component }}-tools
        if: steps.idempotency-tools.outputs.exit_code != '0' || contains(steps.idempotency-tools.outputs.stderr_output, 'IDEMPOTENCY_VIOLATION')
        run: |
          echo "Idempotency check failed for ${{ matrix.component }}-tools"
          echo "Error output:"
          echo "${{ steps.idempotency-tools.outputs.stderr_output }}"
          echo "Exit code: ${{ steps.idempotency-tools.outputs.exit_code }}"
          exit 1
