name: Setup macOS and Shell

on:
  workflow_call:

jobs:
  setup-macos:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Apply macOS system defaults
        run: just cmn-apply-defaults
        
      - name: Backup current system defaults
        run: just cmn-backup-defaults
        
      - name: Verify system defaults application
        run: |
          just cmn-backup-defaults
          git diff --exit-code config/common/system-defaults/system-defaults.yml
