name: Setup Node.js and LLM Tools

on:
  workflow_call:

jobs:
  setup-nodejs:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Add ansible venv to PATH
        run: echo "$HOME/.local/pipx/venvs/ansible/bin" >> $GITHUB_PATH

      - name: Run nodejs-platform setup
        run: just cmn-nodejs-platform

      - name: Run cmn-nodejs-tools setup
        run: just cmn-nodejs-tools

      - name: Setup Claude Code
        run: just cmn-claude

      - name: Setup Gemini CLI
        run: just cmn-gemini

      - name: Setup Codex
        run: just cmn-codex

      - name: Setup slash commands
        run: just cmn-slash
