name: Setup Homebrew

on:
  workflow_call:

jobs:
  setup-homebrew:
    runs-on: macos-15
    env:
      PATH: "$PATH:$HOME/.local/bin"
    strategy:
      fail-fast: false
      matrix:
        config_dir:
          - config/common
          - config/macbook-only
          - config/mac-mini-only
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make setup

      - name: Setup GitHub authentication for Homebrew
        run: |
          echo "🔑 CI環境用のGitHub認証を設定中..."
          # 認証情報を環境変数に設定
          echo "HOMEBREW_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          # Gitの認証設定
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}"
          echo "✅ GitHub認証の設定が完了しました"
        shell: bash

      - name: Run Homebrew setup for ${{ matrix.config_dir }}
        id: setup
        run: ansible-playbook -i ansible/hosts ansible/playbook.yml --tags "brew" -e "config_dir_abs_path=${{ github.workspace }}/${{ matrix.config_dir }}"

