name: Setup Sub Languages

on:
  workflow_call:

jobs:
  setup-base:
    uses: ./.github/workflows/setup-base.yml

  setup-ruby:
    needs: setup-base
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruby
        run: just cmn-ruby