name: Setup macOS and Shell

on:
  workflow_call:

jobs:
  setup-macos:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run apply.sh
        run: ./apply.sh
