name: Setup Shell

on:
  workflow_call:

jobs:
  setup-shell:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Setup shell configuration
        run: just cmn-shell

      - name: Test shell aliases functionality
        shell: zsh {0}
        run: |
          set -euo pipefail
          source ~/.zshrc
          mk --version