name: Setup Python

on:
  workflow_call:

jobs:
  setup-python:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run python.sh for setup
        id: setup
        run: ./scripts/python.sh

      - name: Run python.sh for idempotency check
        id: idempotency
        run: |
          exec 3>&1
          stderr_output=$(./scripts/python.sh 2>&1 | tee /dev/fd/3)
          echo "stderr_output<<EOF" >> $GITHUB_OUTPUT
          echo "$stderr_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Verify idempotency
        if: contains(steps.idempotency.outputs.stderr_output, 'IDEMPOTENCY_VIOLATION')
        run: |
          echo "Idempotency check failed for python.sh"
          echo "Error output:"
          echo "${{ steps.idempotency.outputs.stderr_output }}"
          exit 1
