name: Setup Node

on:
  workflow_call:

jobs:
  setup-node:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Node.js setup
        id: setup
        run: make node

      - name: Run Node.js setup for idempotency check
        id: idempotency
        run: |
          set -o pipefail
          stderr_output=$( (make node >/dev/null) 2>&1 || true )
          {
            echo "stderr_output<<EOF"
            echo "${stderr_output}"
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"

      - name: Verify idempotency
        if: contains(steps.idempotency.outputs.stderr_output, 'IDEMPOTENCY_VIOLATION')
        run: |
          echo "Idempotency check failed for node.sh"
          echo "Error output:"
          echo "${{ steps.idempotency.outputs.stderr_output }}"
          exit 1
