name: Setup Docker

on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Install Colima + Docker
        run: |
          brew install colima docker
          colima start --cpu 2 --memory 4 --disk 10

      - name: Pull Docker images
        run: just cmn-docker-images