name: Setup macOS and Shell

on:
  workflow_call:

jobs:
  setup-macos:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply macOS system defaults
        run: make apply-defaults CONFIG_DIR=config/common

      - name: Re-run backup to check for idempotency
        run: make backup-defaults CONFIG_DIR=config/common

      - name: Verify that system defaults file is unchanged
        run: |
          git diff --exit-code -- config/common/system-defaults/system-defaults.sh
