name: Setup IDE

on:
  workflow_call:

jobs:
  setup-ide:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        tag:
          - vscode
          - antigravity
          - zed
          - xcode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - name: Setup Ansible environment
        uses: ./.github/actions/setup-ansible

      - name: Run ${{ matrix.tag }} setup
        run: mise exec -- just run make ${{ matrix.tag }}
