name: Setup Go

on:
  workflow_call:

jobs:
  setup-go:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - name: Setup Ansible environment
        uses: ./.github/actions/setup-ansible

      - name: Run go-platform setup
        run: mise exec -- just run make go-platform

      - name: Run go-tools setup
        run: mise exec -- just run make go-tools
