name: Setup Platform Tools

on:
  workflow_call:

jobs:
  setup-platform-tools:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        component: [python]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Run ${{ matrix.component }}-platform setup
        run: just cmn-${{ matrix.component }}-platform

      - name: Run cmn-${{ matrix.component }}-tools setup
        run: just cmn-${{ matrix.component }}-tools

      - name: Run mbk-${{ matrix.component }}-tools setup
        run: just mbk-${{ matrix.component }}-tools

      - name: Run mmn-${{ matrix.component }}-tools setup
        run: just mmn-${{ matrix.component }}-tools
        