name: Setup System

on:
  workflow_call:

jobs:
  setup-system:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew and just
        run: make base

      - name: Setup Git configuration
        run: just cmn-git

      - name: Setup GitHub CLI configuration
        run: just cmn-gh

      - name: Setup JJ configuration
        run: just cmn-jj

      - name: Setup shell configuration
        run: just cmn-shell
        
      - name: Test shell aliases functionality
        shell: zsh {0}
        run: |
          set -euo pipefail
          source ~/.zshrc
          mk --version

      - name: Setup SSH configuration
        run: just cmn-ssh

      - name: Setup MCP configuration
        run: just cmn-mcp

      - name: Apply macOS system defaults
        run: just cmn-apply-system
        
      - name: Verify system defaults application
        run: |
          just cmn-backup-system
          git diff --exit-code config/common/system/system.yml
          
      - name: Setup GitHub authentication for Homebrew
        run: |
          echo "🔑 Setting up GitHub authentication for CI environment..."
          # Set authentication information in environment variables
          echo "HOMEBREW_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          # Configure Git authentication
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}"
          echo "✅ GitHub authentication setup completed"
        shell: bash

      - name: Run Homebrew formulae setup for common
        run: just cmn-formulae