name: Setup Python

on:
  workflow_call:

jobs:
  setup-python:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        tag:
          - python-platform
          - python-tools
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - name: Setup Ansible environment
        uses: ./.github/actions/setup-ansible

      - name: Run ${{ matrix.tag }} setup
        run: mise exec -- just run make ${{ matrix.tag }}
