name: Verify macOS Backup Script

on:
  workflow_call:

jobs:
  verify:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execution permission
        run: chmod +x macos/backup.sh

      - name: Run backup script
        run: ./macos/backup.sh

      - name: Check if backup files are generated
        run: |
          if [ -z "$(ls -A macos/default)" ]; then
            echo "No backup files were generated in macos/default."
            exit 1
          fi
          echo "Backup files generated successfully."
