name: Verify macOS Backup Script

on:
  workflow_call:

jobs:
  verify:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: brew install shellcheck

      - name: Grant execution permission
        run: chmod +x macos/config/macos/backup_settings.sh

      - name: Run backup script
        run: ./macos/config/macos/backup_settings.sh

      - name: Check if settings.sh is generated
        run: test -f /tmp/macos-settings.sh

      - name: Lint generated settings.sh
        run: shellcheck /tmp/macos-settings.sh

      - name: Clean up temporary file
        run: rm -f /tmp/macos-settings.sh
