---
- name: "Ensure Codex configuration directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env.HOME }}/.codex"
    - "{{ ansible_env.HOME }}/.codex/prompts"

- name: "Copy Codex configuration file"
  ansible.builtin.copy:
    src: "{{ config_dir_abs_path }}/aiding/codex/config.toml"
    dest: "{{ ansible_env.HOME }}/.codex/config.toml"
    mode: '0644'

- name: "Substitute environment variables in Codex configuration"
  ansible.builtin.replace:
    path: "{{ ansible_env.HOME }}/.codex/config.toml"
    regexp: '\$\{GITHUB_PERSONAL_ACCESS_TOKEN\}'
    replace: "{{ lookup('env', 'GITHUB_PERSONAL_ACCESS_TOKEN') }}"
  when: lookup('env', 'GITHUB_PERSONAL_ACCESS_TOKEN') != ""

- name: "Symlink Codex AGENTS file"
  ansible.builtin.file:
    src: "{{ config_dir_abs_path }}/aiding/codex/AGENTS.md"
    dest: "{{ ansible_env.HOME }}/.codex/AGENTS.md"
    state: link
    force: true
